"""oidc provider

Revision ID: 71abf2f827c3
Revises: 621afbb84ee2
Create Date: 2026-10-09 15:57:05.456239

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "71abf2f827c3"
down_revision: str | Sequence[str] | None = "621afbb84ee2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("client_secret_hash", sa.LargeBinary(), nullable=True),
        sa.Column("is_confidential", sa.Boolean(), nullable=False),
        sa.Column("redirect_uris", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("post_logout_redirect_uris", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("allowed_scopes", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_clients")),
        sa.UniqueConstraint("client_id", name=op.f("uq_oauth_clients_client_id")),
    )
    op.create_table(
        "oidc_signing_keys",
        sa.Column("kid", sa.String(length=64), nullable=False),
        sa.Column("alg", sa.String(length=16), nullable=False),
        sa.Column("public_jwk", sa.Text(), nullable=False),
        sa.Column("encrypted_private_jwk", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("kid", name=op.f("pk_oidc_signing_keys")),
    )
    op.create_table(
        "oauth_consents",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["oauth_clients.id"],
            name=op.f("fk_oauth_consents_client_id_oauth_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_consents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "client_id", name=op.f("pk_oauth_consents")),
    )
    op.create_table(
        "oauth_refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("auth_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["oauth_clients.id"],
            name=op.f("fk_oauth_refresh_tokens_client_id_oauth_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_oauth_refresh_tokens_token_hash")),
    )
    op.create_index(
        "ix_oauth_refresh_tokens_family_id", "oauth_refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(
        "ix_oauth_refresh_tokens_user_client",
        "oauth_refresh_tokens",
        ["user_id", "client_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Client-management permissions, granted to admins.
    for name, description in (
        ("clients:read", "View registered OIDC clients"),
        ("clients:write", "Register, edit and disable OIDC clients"),
    ):
        op.execute(
            sa.text(
                "INSERT INTO permissions (id, name, description) VALUES (gen_random_uuid(), :n, :d)"
            ).bindparams(n=name, d=description)
        )
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) "
                "SELECT r.id, p.id FROM roles r, permissions p "
                "WHERE r.name = 'admin' AND p.name = :n"
            ).bindparams(n=name)
        )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM permissions WHERE name IN ('clients:read', 'clients:write')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_oauth_refresh_tokens_user_client", table_name="oauth_refresh_tokens")
    op.drop_index("ix_oauth_refresh_tokens_family_id", table_name="oauth_refresh_tokens")
    op.drop_table("oauth_refresh_tokens")
    op.drop_table("oauth_consents")
    op.drop_table("oidc_signing_keys")
    op.drop_table("oauth_clients")
    # ### end Alembic commands ###
