"""mfa recovery step-up email change

Revision ID: dbc04d2b3b69
Revises: 167157119efb
Create Date: 2026-10-09 15:00:14.876716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbc04d2b3b69"
down_revision: str | Sequence[str] | None = "167157119efb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic doesn't diff enum values. ADD VALUE is allowed inside a transaction on
    # PostgreSQL 12+ (the new value just can't be used in the same transaction).
    op.execute("ALTER TYPE email_token_purpose ADD VALUE IF NOT EXISTS 'email_change'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recovery_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_recovery_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_codes")),
    )
    op.create_index("ix_recovery_codes_user_id", "recovery_codes", ["user_id"], unique=False)
    op.create_table(
        "totp_credentials",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("encrypted_secret", sa.Text(), nullable=False),
        sa.Column("last_used_step", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_totp_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_totp_credentials")),
    )
    op.add_column("email_tokens", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_email_tokens_user_id_users"),
        "email_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "sessions", sa.Column("reauthenticated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # PostgreSQL can't drop an enum value: rebuild the type without it.
    op.execute("DELETE FROM email_tokens WHERE purpose = 'email_change'")
    op.execute("ALTER TYPE email_token_purpose RENAME TO email_token_purpose_old")
    op.execute("CREATE TYPE email_token_purpose AS ENUM ('signup')")
    op.execute(
        "ALTER TABLE email_tokens ALTER COLUMN purpose TYPE email_token_purpose "
        "USING purpose::text::email_token_purpose"
    )
    op.execute("DROP TYPE email_token_purpose_old")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "reauthenticated_at")
    op.drop_constraint(op.f("fk_email_tokens_user_id_users"), "email_tokens", type_="foreignkey")
    op.drop_column("email_tokens", "user_id")
    op.drop_table("totp_credentials")
    op.drop_index("ix_recovery_codes_user_id", table_name="recovery_codes")
    op.drop_table("recovery_codes")
    # ### end Alembic commands ###
