"""rbac

Revision ID: 621afbb84ee2
Revises: eabc1088b1db
Create Date: 2026-10-09 15:34:35.697658

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "621afbb84ee2"
down_revision: str | Sequence[str] | None = "eabc1088b1db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("name", name=op.f("uq_permissions_name")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    # ### end Alembic commands ###

    # Seed data is inlined (not imported from keygate.rbac.catalog) so this migration
    # stays a frozen snapshot even if the catalogue changes later.
    permissions = {
        "users:read": "Search and view user accounts",
        "users:write": "Suspend and unsuspend user accounts",
        "users:sessions:revoke": "Revoke other users' sessions",
        "roles:assign": "Grant and revoke roles",
        "audit:read": "Read the audit log",
    }
    roles = {
        "user": ("Default role: manages only their own account", []),
        "auditor": (
            "Read-only access to the audit log and user directory",
            ["audit:read", "users:read"],
        ),
        "admin": ("Full administrative access", list(permissions)),
    }
    for name, description in permissions.items():
        op.execute(
            sa.text(
                "INSERT INTO permissions (id, name, description) VALUES (gen_random_uuid(), :n, :d)"
            ).bindparams(n=name, d=description)
        )
    for name, (description, perms) in roles.items():
        op.execute(
            sa.text(
                "INSERT INTO roles (id, name, description) VALUES (gen_random_uuid(), :n, :d)"
            ).bindparams(n=name, d=description)
        )
        for perm in perms:
            op.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_id) "
                    "SELECT r.id, p.id FROM roles r, permissions p "
                    "WHERE r.name = :r AND p.name = :p"
                ).bindparams(r=name, p=perm)
            )
    # Every existing account gets the default role.
    op.execute(
        "INSERT INTO user_roles (user_id, role_id, granted_at) "
        "SELECT u.id, r.id, now() FROM users u, roles r WHERE r.name = 'user'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###
